USE [master]
GO

/****** Object:  Database [DatabaseQLKho]    Script Date: 5/28/2019 8:46:13 AM ******/
CREATE DATABASE [DatabaseQLKho]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DatabaseQLKho', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DatabaseQLKho.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DatabaseQLKho_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DatabaseQLKho_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DatabaseQLKho] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DatabaseQLKho].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DatabaseQLKho] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET ARITHABORT OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DatabaseQLKho] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DatabaseQLKho] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DatabaseQLKho] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DatabaseQLKho] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET RECOVERY FULL 
GO

ALTER DATABASE [DatabaseQLKho] SET  MULTI_USER 
GO

ALTER DATABASE [DatabaseQLKho] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DatabaseQLKho] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DatabaseQLKho] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DatabaseQLKho] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DatabaseQLKho] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DatabaseQLKho] SET QUERY_STORE = OFF
GO

USE [DatabaseQLKho]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DatabaseQLKho] SET  READ_WRITE 
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[CHITIETPHIEUNHAP]    Script Date: 5/28/2019 8:46:38 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHITIETPHIEUNHAP](
	[MaHangHoa] [nvarchar](50) NOT NULL,
	[MaPhieuNhap] [nvarchar](50) NOT NULL,
	[SoLuongNhap] [int] NOT NULL,
	[DienGiai] [nvarchar](max) NULL,
 CONSTRAINT [PK_CHITIETPHIEUNHAP] PRIMARY KEY CLUSTERED 
(
	[MaHangHoa] ASC,
	[MaPhieuNhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CHITIETPHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUNHAP_HANGHOA] FOREIGN KEY([MaHangHoa])
REFERENCES [dbo].[HANGHOA] ([MaHangHoa])
GO

ALTER TABLE [dbo].[CHITIETPHIEUNHAP] CHECK CONSTRAINT [FK_CHITIETPHIEUNHAP_HANGHOA]
GO

ALTER TABLE [dbo].[CHITIETPHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUNHAP_PHIEUNHAP] FOREIGN KEY([MaPhieuNhap])
REFERENCES [dbo].[PHIEUNHAP] ([MaPhieuNhap])
GO

ALTER TABLE [dbo].[CHITIETPHIEUNHAP] CHECK CONSTRAINT [FK_CHITIETPHIEUNHAP_PHIEUNHAP]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[CHITIETPHIEUXUAT]    Script Date: 5/28/2019 8:46:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHITIETPHIEUXUAT](
	[MaHangHoa] [nvarchar](50) NOT NULL,
	[MaPhieuXuat] [nvarchar](50) NOT NULL,
	[SoLuongXuat] [int] NOT NULL,
	[DienGiai] [nvarchar](max) NULL,
 CONSTRAINT [PK_CHITIETPHIEUXUAT_1] PRIMARY KEY CLUSTERED 
(
	[MaHangHoa] ASC,
	[MaPhieuXuat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUXUAT_HANGHOA] FOREIGN KEY([MaHangHoa])
REFERENCES [dbo].[HANGHOA] ([MaHangHoa])
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT] CHECK CONSTRAINT [FK_CHITIETPHIEUXUAT_HANGHOA]
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETPHIEUXUAT_PHIEUXUAT] FOREIGN KEY([MaPhieuXuat])
REFERENCES [dbo].[PHIEUXUAT] ([MaPhieuXuat])
GO

ALTER TABLE [dbo].[CHITIETPHIEUXUAT] CHECK CONSTRAINT [FK_CHITIETPHIEUXUAT_PHIEUXUAT]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[CHUCVU]    Script Date: 5/28/2019 8:47:11 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHUCVU](
	[MaChucVu] [nvarchar](50) NOT NULL,
	[TenChucVu] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CHUCVU] PRIMARY KEY CLUSTERED 
(
	[MaChucVu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[DONVITINH]    Script Date: 5/28/2019 8:47:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DONVITINH](
	[MaDonViTinh] [nvarchar](50) NOT NULL,
	[TenDonViTinh] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DONVITINH] PRIMARY KEY CLUSTERED 
(
	[MaDonViTinh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[GIOIHANTON]    Script Date: 5/28/2019 8:48:00 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GIOIHANTON](
	[MaGioiHanTon] [nvarchar](50) NOT NULL,
	[MaHangHoa] [nvarchar](50) NOT NULL,
	[TonToiThieu] [nvarchar](50) NOT NULL,
	[TonToiDa] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_GIOIHANTON] PRIMARY KEY CLUSTERED 
(
	[MaGioiHanTon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GIOIHANTON]  WITH CHECK ADD  CONSTRAINT [FK_GIOIHANTON_HANGHOA] FOREIGN KEY([MaHangHoa])
REFERENCES [dbo].[HANGHOA] ([MaHangHoa])
GO

ALTER TABLE [dbo].[GIOIHANTON] CHECK CONSTRAINT [FK_GIOIHANTON_HANGHOA]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[HANGHOA]    Script Date: 5/28/2019 8:48:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HANGHOA](
	[MaHangHoa] [nvarchar](50) NOT NULL,
	[TenHangHoa] [nvarchar](max) NOT NULL,
	[MaTrangThaiHang] [nvarchar](50) NOT NULL,
	[MaDonViTinh] [nvarchar](50) NOT NULL,
	[MaNhaSanXuat] [nvarchar](50) NOT NULL,
	[MaLoaiHangHoa] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_HANGHOA] PRIMARY KEY CLUSTERED 
(
	[MaHangHoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[HANGHOA]  WITH CHECK ADD  CONSTRAINT [FK_HANGHOA_DONVITINH] FOREIGN KEY([MaDonViTinh])
REFERENCES [dbo].[DONVITINH] ([MaDonViTinh])
GO

ALTER TABLE [dbo].[HANGHOA] CHECK CONSTRAINT [FK_HANGHOA_DONVITINH]
GO

ALTER TABLE [dbo].[HANGHOA]  WITH CHECK ADD  CONSTRAINT [FK_HANGHOA_LOAIHANGHOA] FOREIGN KEY([MaLoaiHangHoa])
REFERENCES [dbo].[LOAIHANGHOA] ([MaLoaiHangHoa])
GO

ALTER TABLE [dbo].[HANGHOA] CHECK CONSTRAINT [FK_HANGHOA_LOAIHANGHOA]
GO

ALTER TABLE [dbo].[HANGHOA]  WITH CHECK ADD  CONSTRAINT [FK_HANGHOA_NHASANXUAT] FOREIGN KEY([MaNhaSanXuat])
REFERENCES [dbo].[NHASANXUAT] ([MaNhaSanXuat])
GO

ALTER TABLE [dbo].[HANGHOA] CHECK CONSTRAINT [FK_HANGHOA_NHASANXUAT]
GO

ALTER TABLE [dbo].[HANGHOA]  WITH CHECK ADD  CONSTRAINT [FK_HANGHOA_TRANGTHAIHANGHOA] FOREIGN KEY([MaTrangThaiHang])
REFERENCES [dbo].[TRANGTHAIHANGHOA] ([MaTrangThaiHang])
GO

ALTER TABLE [dbo].[HANGHOA] CHECK CONSTRAINT [FK_HANGHOA_TRANGTHAIHANGHOA]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[LOAIHANGHOA]    Script Date: 5/28/2019 8:49:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOAIHANGHOA](
	[MaLoaiHangHoa] [nvarchar](50) NOT NULL,
	[TenLoaiHangHoa] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LOAIHANGHOA] PRIMARY KEY CLUSTERED 
(
	[MaLoaiHangHoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[LOAIPHIEUXUATNHAP]    Script Date: 5/28/2019 8:50:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOAIPHIEUXUATNHAP](
	[MaLoaiPhieuXuatNhap] [nvarchar](50) NOT NULL,
	[TenLoaiPhieu] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_LOAIPHIEUXUATNHAP] PRIMARY KEY CLUSTERED 
(
	[MaLoaiPhieuXuatNhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 5/28/2019 8:50:28 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NHANVIEN](
	[MaNhanVien] [nvarchar](50) NOT NULL,
	[TenNhanVien] [nvarchar](max) NOT NULL,
	[TaiKhoan] [nvarchar](50) NULL,
	[MatKhau] [nvarchar](20) NULL,
	[MaTrangThaiNhanVien] [nvarchar](50) NOT NULL,
	[MaChucVu] [nvarchar](50) NOT NULL,
	[SoDienThoai] [nvarchar](20) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MaNhanVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHANVIEN_CHUCVU] FOREIGN KEY([MaChucVu])
REFERENCES [dbo].[CHUCVU] ([MaChucVu])
GO

ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_CHUCVU]
GO

ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHANVIEN_NHANVIEN] FOREIGN KEY([MaTrangThaiNhanVien])
REFERENCES [dbo].[TRANGTHAINHANVIEN] ([MaTrangThaiNhanVien])
GO

ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_NHANVIEN]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[NHASANXUAT]    Script Date: 5/28/2019 8:50:38 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NHASANXUAT](
	[MaNhaSanXuat] [nvarchar](50) NOT NULL,
	[TenNhaSanXuat] [nvarchar](max) NOT NULL,
	[DiaChi] [nvarchar](max) NOT NULL,
	[DienThoai] [nchar](20) NOT NULL,
 CONSTRAINT [PK_NHASANXUAT] PRIMARY KEY CLUSTERED 
(
	[MaNhaSanXuat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[PHIEUNHAP]    Script Date: 5/28/2019 8:50:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEUNHAP](
	[MaPhieuNhap] [nvarchar](50) NOT NULL,
	[MaLoaiPhieuXuatNhap] [nvarchar](50) NOT NULL,
	[MaNhanVien] [nvarchar](50) NOT NULL,
	[MaTrangThaiPhieu] [nvarchar](50) NOT NULL,
	[NgayLapPhieu] [date] NULL,
	[NgayNhap] [date] NULL,
	[DiaChiKhachHang] [nvarchar](max) NULL,
	[TongSoLuongNhap] [int] NOT NULL,
	[NoiDung] [nvarchar](max) NULL,
 CONSTRAINT [PK_PHIEUNHAP] PRIMARY KEY CLUSTERED 
(
	[MaPhieuNhap] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUNHAP_LOAIPHIEUXUATNHAP] FOREIGN KEY([MaLoaiPhieuXuatNhap])
REFERENCES [dbo].[LOAIPHIEUXUATNHAP] ([MaLoaiPhieuXuatNhap])
GO

ALTER TABLE [dbo].[PHIEUNHAP] CHECK CONSTRAINT [FK_PHIEUNHAP_LOAIPHIEUXUATNHAP]
GO

ALTER TABLE [dbo].[PHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUNHAP_NHANVIEN] FOREIGN KEY([MaNhanVien])
REFERENCES [dbo].[NHANVIEN] ([MaNhanVien])
GO

ALTER TABLE [dbo].[PHIEUNHAP] CHECK CONSTRAINT [FK_PHIEUNHAP_NHANVIEN]
GO

ALTER TABLE [dbo].[PHIEUNHAP]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUNHAP_TRANGTHAINHAPXUAT] FOREIGN KEY([MaTrangThaiPhieu])
REFERENCES [dbo].[TRANGTHAINHAPXUAT] ([MaTrangThaiPhieu])
GO

ALTER TABLE [dbo].[PHIEUNHAP] CHECK CONSTRAINT [FK_PHIEUNHAP_TRANGTHAINHAPXUAT]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[PHIEUXUAT]    Script Date: 5/28/2019 8:51:09 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PHIEUXUAT](
	[MaPhieuXuat] [nvarchar](50) NOT NULL,
	[MaLoaiPhieuXuat] [nvarchar](50) NOT NULL,
	[MaNhanVien] [nvarchar](50) NOT NULL,
	[MaTrangThaiPhieu] [nvarchar](50) NOT NULL,
	[NgayLapPhieu] [date] NOT NULL,
	[NgayXuat] [date] NOT NULL,
	[KhachHang] [nvarchar](max) NULL,
	[DiaChiKhachHnag] [nvarchar](max) NULL,
 CONSTRAINT [PK_PHIEUXUAT] PRIMARY KEY CLUSTERED 
(
	[MaPhieuXuat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUXUAT_NHANVIEN] FOREIGN KEY([MaNhanVien])
REFERENCES [dbo].[NHANVIEN] ([MaNhanVien])
GO

ALTER TABLE [dbo].[PHIEUXUAT] CHECK CONSTRAINT [FK_PHIEUXUAT_NHANVIEN]
GO

ALTER TABLE [dbo].[PHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUXUAT_PHIEUXUAT] FOREIGN KEY([MaLoaiPhieuXuat])
REFERENCES [dbo].[LOAIPHIEUXUATNHAP] ([MaLoaiPhieuXuatNhap])
GO

ALTER TABLE [dbo].[PHIEUXUAT] CHECK CONSTRAINT [FK_PHIEUXUAT_PHIEUXUAT]
GO

ALTER TABLE [dbo].[PHIEUXUAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUXUAT_TRANGTHAINHAPXUAT] FOREIGN KEY([MaTrangThaiPhieu])
REFERENCES [dbo].[TRANGTHAINHAPXUAT] ([MaTrangThaiPhieu])
GO

ALTER TABLE [dbo].[PHIEUXUAT] CHECK CONSTRAINT [FK_PHIEUXUAT_TRANGTHAINHAPXUAT]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[TRANGTHAIHANGHOA]    Script Date: 5/28/2019 8:51:31 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRANGTHAIHANGHOA](
	[MaTrangThaiHang] [nvarchar](50) NOT NULL,
	[TenTrangTHaiHang] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TRANGTHAIHANGHOA] PRIMARY KEY CLUSTERED 
(
	[MaTrangThaiHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[TRANGTHAINHANVIEN]    Script Date: 5/28/2019 8:51:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRANGTHAINHANVIEN](
	[MaTrangThaiNhanVien] [nvarchar](50) NOT NULL,
	[TenTrangThaiNhaVien] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TRANGTHAINHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MaTrangThaiNhanVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [DatabaseQLKho]
GO

/****** Object:  Table [dbo].[TRANGTHAINHAPXUAT]    Script Date: 5/28/2019 8:51:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRANGTHAINHAPXUAT](
	[MaTrangThaiPhieu] [nvarchar](50) NOT NULL,
	[TenTrangThaiPhieu] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TRANGTHAINHAPXUAT] PRIMARY KEY CLUSTERED 
(
	[MaTrangThaiPhieu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


